### ISSUE TITLE
[LanguageManager] Custom Editor Window to modify Translations

### ISSUE THREAD

**Issue by michaelholly** [GamesResearchTUG/gearUtilities#14]
Custom Unity Editor Window to add new translations or to modify existing translations.

**Comment by sandra-bre** [comment]
![image](https://user-images.githubusercontent.com/9962095/85306465-ca537e00-b4ae-11ea-962b-7780b03b75ac.png)
![image](https://user-images.githubusercontent.com/9962095/85306479-d3dce600-b4ae-11ea-82e7-56a08a283051.png)
